# Generated by Django 5.1.1 on 2024-09-11 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_recipe_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='recipe_views_count',
            field=models.IntegerField(default=1),
        ),
    ]
