# Generated by Django 5.1.1 on 2024-09-11 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_recipe_recipe_views_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='recipe_image',
        ),
        migrations.AddField(
            model_name='recipe',
            name='recipe_image_base64',
            field=models.TextField(blank=True, null=True),
        ),
    ]
